solidity:
    image: smartbugs/security:usolc
    entrypoint: $BIN/run_solidity $FILENAME $BIN
    user: 0
    solc: yes
    bin: scripts
runtime:
    image: smartbugs/security:usolc
    command: --livestatusfile /results/live.json --output /results/results.json -fh $FILENAME
output: /results/
info: Securify uses formal verification, also relying on static analysis checks. Securify's analysis consists of two steps. First, it symbolically analyzes the contract's dependency graph to extract precise semantic information from the code. Then, it checks compliance and violation patterns that capture sufficient conditions for proving if a property holds or not.
