solidity:
    image: "smartbugs/manticore:0.3.7"
    entrypoint: \"$BIN/run_solidity\" \"$FILENAME\" \"$BIN\"
    user: 0
    solc: yes
    bin: scripts
output: /results
info: Manticore is a symbolic execution tool for analysis of smart contracts and binaries.
