solidity:
    image: smartbugs/maian:solc5.10
    entrypoint: $BIN/run_solidity "$FILENAME" "$BIN"
    user: 0
    solc: yes
    bin: scripts
bytecode:
    image: smartbugs/maian:solc5.10
    entrypoint: $BIN/run_bytecode "$FILENAME"
    user: 0
    bin: scripts
runtime:
    image: smartbugs/maian:solc5.10
    entrypoint: $BIN/run_runtime "$FILENAME"
    user: 0
    bin: scripts
info: Maian is a tool for the automated detection of buggy Ethereum smart contracts of type 'prodigal', 'suicidal', and 'greedy'.
