alias:
    - conkas
    - ethainter
    - ethor
    - honeybadger
    - maian
    - madmax
    - mythril
    - osiris
    - oyente
    - pakala
    - securify
    - solhint
    - teether
    - vandal
