docker_image:
        default: smartbugs/pakala:1.1.10
cmd_bytecode: /runPakala.sh
output_parser: Pakala
info: Pakala is a tool to search for exploitable bugs in Ethereum smart contracts and a symbolic execution engine for the Ethereum Virtual Machine.
