name: ConFuzzius
info: A data dependency-aware hybrid fuzzer for Ethereum smart contracts
origin: https://github.com/christoftorres/ConFuzzius
image: christoftorres/confuzzius

solidity:
    command: "'$BIN/do_solidity' '$FILENAME' '$TIMEOUT' '$BIN'"
    output: /root/results.json
    bin: scripts
    solc: yes
