name: Vandal
origin: https://github.com/usyd-blockchain/vandal
version: "#d2b0043"
info: Vandal is a static program analysis framework for Ethereum smart contract bytecode.
runtime:
    image: smartbugs/vandal
    command: /runVandal.sh $FILENAME
