solidity:
    image: smartbugs/oyente:480e725
    entrypoint: $BIN/run_solidity $FILENAME $BIN
    user: 0
    solc: yes
    bin: scripts
runtime:
    image: smartbugs/oyente:480e725
    command: -b  -s $FILENAME
output_parser: Oyente
info: Oyente runs on symbolic execution, determines which inputs cause which program branches to execute, to find potential security vulnerabilities. Oyente works directly with EVM bytecode without access high level representation and does not provide soundness nor completeness.
