name: SmartBugs CI
on: [push]
jobs:
  run-all-once:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: ["all"]
        contract: ["'.github/sample/*'"]
        python-version: ["3.6.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: ./setup-venv.sh
      - name: Execute ${{ matrix.tool }} on ${{ matrix.contract }}
        run: source venv/bin/activate; ./smartbugs -t ${{ matrix.tool }} -f ${{ matrix.contract }} --sarif --runid github
      - name: Reparse results  of ${{matrix.tool}} on ${{ matrix.contract }}
        run: ./reparse results
      - name: Verify results of ${{matrix.tool}} on ${{ matrix.contract }}
        run: ./results2csv -x start duration -- results | diff - .github/sample.csv
