name: SmartBugs CI
on: [push]
jobs:
  run-all-once:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: ["all"]
        contract: [".github/sample/*"]
        python-version: ["3.6.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup
        run: ./setup-venv.sh
      - name: Execute ${{ matrix.tool }} on ${{ matrix.contract }}
        run: source venv/bin/activate; ./smartbugs -t ${{ matrix.tool }} --logfile test.log --results test_execution -f ${{ matrix.contract }};
      - name: Results of ${{matrix.tool}} on ${{ matrix.contract }}
        run: cat test_execution*/{smartbugs.json,result.log}
